name: "CI"
on:
  pull_request:
  push:
jobs:
  tests:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6
    - uses: cachix/install-nix-action@91a071959513ca103b54280ac0bef5b825791d4d # v31
    - run: ./ci.sh
